class TopicClassifier {
  static const List<String> topics = [
    'Đồ gia dụng', // 0
    'Thiên nhiên', // 1
    'Công nghệ', // 2
    'Đồ ăn', // 3
    'Con vật', // 4
    'Phương tiện', // 5
    'Hoạt động', // 6
    'Màu sắc', // 7
    'Không gian', // 8
    'Thời gian', // 9
  ];

  static const Map<String, List<String>> keywords = {
    'Đồ gia dụng': [
      'chair',
      'table',
      'bed',
      'lamp',
      'door',
      'window',
      'sofa',
      'cabinet',
      'ghế',
      'bàn',
      'giường',
      'đèn',
      'cửa',
      'tủ',
      'sofa',
      'nồi',
      'chảo',
      'kitchen',
      'utensil',
      'plate',
      'cup',
      'spoon',
      'fork',
      'dĩa',
      'cốc',
      'muỗng',
    ],
    'Thiên nhiên': [
      'tree',
      'flower',
      'mountain',
      'river',
      'sky',
      'sun',
      'moon',
      'cloud',
      'rain',
      'cây',
      'hoa',
      'núi',
      'sông',
      'trời',
      'mặt trời',
      'mặt trăng',
      'mây',
      'mưa',
      'forest',
      'ocean',
      'sea',
      'beach',
      'grass',
      'stone',
      'rock',
      'water',
      'rừng',
      'biển',
      'bãi biển',
      'cỏ',
      'đá',
    ],
    'Công nghệ': [
      'computer',
      'phone',
      'laptop',
      'tablet',
      'robot',
      'camera',
      'screen',
      'keyboard',
      'máy tính',
      'điện thoại',
      'robot',
      'camera',
      'màn hình',
      'bàn phím',
      'chuột',
      'electric',
      'digital',
      'software',
      'app',
      'internet',
      'wifi',
      'server',
      'điện tử',
      'kỹ thuật số',
      'phần mềm',
    ],
    'Đồ ăn': [
      'apple',
      'banana',
      'bread',
      'rice',
      'meat',
      'fish',
      'chicken',
      'egg',
      'milk',
      'táo',
      'chuối',
      'bánh',
      'cơm',
      'thịt',
      'cá',
      'gà',
      'trứng',
      'sữa',
      'orange',
      'lemon',
      'cheese',
      'sugar',
      'salt',
      'oil',
      'butter',
      'cam',
      'chanh',
      'phô mai',
      'đường',
      'muối',
      'dầu',
      'bơ',
      'đơ',
    ],
    'Con vật': [
      'cat',
      'dog',
      'bird',
      'fish',
      'lion',
      'tiger',
      'elephant',
      'monkey',
      'rabbit',
      'mèo',
      'chó',
      'chim',
      'cá',
      'sư tử',
      'hổ',
      'voi',
      'khỉ',
      'thỏ',
      'horse',
      'cow',
      'pig',
      'sheep',
      'snake',
      'insect',
      'butterfly',
      'spider',
      'ngựa',
      'bò',
      'lợn',
      'cừu',
      'rắn',
      'côn trùng',
      'bươm bướm',
      'nhện',
    ],
    'Phương tiện': [
      'car',
      'bus',
      'train',
      'plane',
      'bike',
      'motorcycle',
      'truck',
      'taxi',
      'boat',
      'ô tô',
      'xe buýt',
      'tàu',
      'máy bay',
      'xe đạp',
      'xe máy',
      'xe tải',
      'taxi',
      'thuyền',
      'helicopter',
      'ship',
      'submarine',
      'bicycle',
      'vehicle',
      'transport',
      'trực thăng',
      'tàu',
      'tàu ngầm',
      'xe cộ',
      'vận tải',
    ],
    'Hoạt động': [
      'run',
      'walk',
      'jump',
      'swim',
      'dance',
      'sing',
      'play',
      'read',
      'write',
      'eat',
      'chạy',
      'bước',
      'nhảy',
      'bơi',
      'nhảy múa',
      'hát',
      'chơi',
      'đọc',
      'viết',
      'ăn',
      'sleep',
      'wake',
      'work',
      'study',
      'cook',
      'clean',
      'paint',
      'draw',
      'ngủ',
      'thức dậy',
      'làm việc',
      'học',
      'nấu ăn',
      'dọn dẹp',
      'vẽ',
    ],
    'Màu sắc': [
      'red',
      'blue',
      'green',
      'yellow',
      'black',
      'white',
      'orange',
      'purple',
      'pink',
      'đỏ',
      'xanh dương',
      'xanh lá',
      'vàng',
      'đen',
      'trắng',
      'cam',
      'tím',
      'hồng',
      'gray',
      'brown',
      'golden',
      'silver',
      'color',
      'bright',
      'dark',
      'light',
      'xám',
      'nâu',
      'vàng kim',
      'bạc',
      'màu',
      'sáng',
      'tối',
    ],
    'Không gian': [
      'house',
      'room',
      'building',
      'street',
      'city',
      'country',
      'door',
      'wall',
      'floor',
      'nhà',
      'phòng',
      'tòa nhà',
      'đường',
      'thành phố',
      'quốc gia',
      'cửa',
      'tường',
      'sàn',
      'ceiling',
      'window',
      'garden',
      'park',
      'office',
      'school',
      'hospital',
      'shop',
      'trần nhà',
      'cửa sổ',
      'khu vườn',
      'công viên',
      'văn phòng',
      'trường',
      'bệnh viện',
    ],
    'Thời gian': [
      'hour',
      'minute',
      'second',
      'day',
      'week',
      'month',
      'year',
      'morning',
      'evening',
      'giờ',
      'phút',
      'giây',
      'ngày',
      'tuần',
      'tháng',
      'năm',
      'sáng',
      'tối',
      'clock',
      'watch',
      'calendar',
      'time',
      'night',
      'noon',
      'midnight',
      'hour',
      'đồng hồ',
      'lịch',
      'đêm',
      'trưa',
      'nửa đêm',
    ],
  };

  /// Classify word vào topic tương ứng dựa trên keyword matching
  static String classifyWord(String word, String meaning) {
    final lowerWord = word.toLowerCase();
    final lowerMeaning = meaning.toLowerCase();
    final combined = '$lowerWord $lowerMeaning';

    // Score cho mỗi topic
    final scores = <String, int>{};
    for (final topic in topics) {
      scores[topic] = 0;
    }

    // Check keyword matching
    for (final topic in topics) {
      final topicKeywords = keywords[topic] ?? [];
      for (final keyword in topicKeywords) {
        if (combined.contains(keyword.toLowerCase())) {
          scores[topic] = (scores[topic] ?? 0) + 1;
        }
      }
    }

    // Find topic với score cao nhất
    String bestTopic = topics[0];
    int maxScore = 0;

    for (final entry in scores.entries) {
      if (entry.value > maxScore) {
        maxScore = entry.value;
        bestTopic = entry.key;
      }
    }

    // Nếu không match keyword, return default
    return maxScore > 0 ? bestTopic : topics[0];
  }

  /// Get topic index
  static int getTopicIndex(String topicName) {
    return topics.indexOf(topicName);
  }

  /// Get topic name from index
  static String getTopicName(int index) {
    return topics.isNotEmpty && index >= 0 && index < topics.length
        ? topics[index]
        : topics[0];
  }
}
