// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcl7i44yBD_Yan9A9H3tOkj3qVSI0wo0A',
    appId: '1:840856064919:web:0b9919af3f10ebe9f6aad2',
    messagingSenderId: '840856064919',
    projectId: 'cardify-9dfed',
    authDomain: 'cardify-9dfed.firebaseapp.com',
    storageBucket: 'cardify-9dfed.firebasestorage.app',
    measurementId: 'G-CHR87MKB2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYGU_Qa4eAsLVo6HIgN282BAkCU2o-n8',
    appId: '1:840856064919:android:6e2307770df03174f6aad2',
    messagingSenderId: '840856064919',
    projectId: 'cardify-9dfed',
    storageBucket: 'cardify-9dfed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIEnkETHiAGGQcCU0LEANKzkpWrwihvqk',
    appId: '1:840856064919:ios:2201968500abef29f6aad2',
    messagingSenderId: '840856064919',
    projectId: 'cardify-9dfed',
    storageBucket: 'cardify-9dfed.firebasestorage.app',
    androidClientId: '840856064919-pct2ctrv3rfd5em7umaqc90beent9qi6.apps.googleusercontent.com',
    iosClientId: '840856064919-ts62ighjdhhvskcl7h2mmmovsebp8oci.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBtl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIEnkETHiAGGQcCU0LEANKzkpWrwihvqk',
    appId: '1:840856064919:ios:2201968500abef29f6aad2',
    messagingSenderId: '840856064919',
    projectId: 'cardify-9dfed',
    storageBucket: 'cardify-9dfed.firebasestorage.app',
    androidClientId: '840856064919-pct2ctrv3rfd5em7umaqc90beent9qi6.apps.googleusercontent.com',
    iosClientId: '840856064919-ts62ighjdhhvskcl7h2mmmovsebp8oci.apps.googleusercontent.com',
    iosBundleId: 'com.example.appBtl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcl7i44yBD_Yan9A9H3tOkj3qVSI0wo0A',
    appId: '1:840856064919:web:385c54b71265106af6aad2',
    messagingSenderId: '840856064919',
    projectId: 'cardify-9dfed',
    authDomain: 'cardify-9dfed.firebaseapp.com',
    storageBucket: 'cardify-9dfed.firebasestorage.app',
    measurementId: 'G-NE439P1B7N',
  );
}
